server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recipe_db
    username: "postgres"
    password: "Suna2001"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

